export enum GamePhases {
  WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
  WAITING_FOR_READY = 'WAITING_FOR_READY',
  FLIPPING_COIN = 'FLIPPING_COIN',
  SPREADING_OBJECT = 'SPREADING_OBJECT',
  PLAYING = 'PLAYING',
  PLAYER_FILL_PLAYING = 'PLAYER_FILL_PLAYING',
  PLAYER_EMPTY_PLAYING = 'PLAYER_EMPTY_PLAYING',
  REACHING_EMPTY_HAND_LIMIT = 'REACHING_EMPTY_HAND_LIMIT',
  GAME_FINISHED = 'GAME_FINISHED',
}
